### ISSUE TITLE
precision errors

### ISSUE THREAD

**Issue by chenyangchenyang** [nrtaylor/CubicSplineClosestPoint#1]
Your project is very good.But I have a question about precision errors with divide zero.How to resolve it?
My test data is

control_points.push_back(WorldSpace(0, 0, 0));
control_points.push_back(WorldSpace(10, 0, 0));
control_points.push_back(WorldSpace(10, 10, 0));
control_points.push_back(WorldSpace(20, 10, 0));
WorldSpace position(5.795, 0.297, 0);

![py](https://user-images.githubusercontent.com/28689129/50483095-142be700-0a25-11e9-9912-a4b9df2c7441.png)

**Comment by nrtaylor** [comment]
Thank you, I will have time to look next week. My guess is for performance, I removed checks like that, but I will reply soon.

- Nic

**Comment by chenyangchenyang** [comment]
Look forward your solution.

togchen

**Comment by nrtaylor** [comment]
Now I recall. Building the sturm sequence is done in double precision because there were precision errors in single. However this test case (I have reproduced here) does not appear to be precision and is independent of the test position:
coefficient = -0.1 * 10 - 2.5
coefficient += 0.2 * 7.5
which means there is something interesting to the geometry of the curve for there to be no remainder.
Just looking at the points on paper, the curve would be a smooth curve with no loops.

I'll need to brush up on the topic as it has been a few years since I wrote this. In the interim, if you have a curve with this pattern, you could add some slight jitter before building the solver. I'll schedule some time for a better investigation.

**Comment by chenyangchenyang** [comment]
yi, Look forward your new solution

**Comment by nrtaylor** [comment]
I worked out the polynomial division, building out the Sturm Sequence by hand as a sanity check, with your example and the third degree polynomial does have a leading coefficient of 0. The rest of the polynomial is still computed correctly.
What I called "remainder_coefficient" and "remainder_sum" are misleading. They are the coefficients of the first degree polynomial quotient from dividing p2 by p1.
The fix that is needed is that if a leading coefficient(s) is zero, there need to be additional quotients coefficients computed. (Note: If p1 is a factor of p2, all remaining values should be 0; I have not looked into if this impacts sign counting yet. Acton's Numerical Methods that Work pg 334 has a brief paragraph that might be relevant.)
So a few things need to happen:
1. rename variables
2. support additional quotient coefficients
3. add tests to make sure I don't impact perf/correctness
4. TBD: handle factor case.

I ran out of time this week, but I will aim to do 1 and 2 next week.

**Comment by nrtaylor** [comment]
I submitted a fix. My old tests still pass and I added a few based around your example but it certainly is not a comprehensive test. The other piece I need to look into is if the algorithm will estimate one extra root. This would not create a wrong result, but would spend extra work computing a solution.
I made some notes to come back later and clean/improve the new code. Thank you for letting me know about this issue! :)

**Comment by chenyangchenyang** [comment]
oh,amazing.
Firstly,Thank you for fix the bug!I have not checked the new code.
Secondly,I suggest this is a better choice for checking robust code using relative error.Test cases will be generated from random numbers.The few error solution will be generated from sample points in curve.
Finally,thanks you for works again!
